# Generated by Django 4.2.7 on 2023-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('path', models.CharField()),
                ('description', models.CharField(blank=True)),
            ],
        ),
    ]
