# Generated by Django 4.2.7 on 2023-11-05 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_point_options_alter_users_options_videoform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoForm',
            new_name='Video',
        ),
    ]
