# Generated by Django 4.2.7 on 2023-11-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_rename_videoform_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
