# Generated by Django 4.2.7 on 2023-11-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_remove_video_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='address',
            field=models.CharField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='video',
            name='camera_name',
            field=models.CharField(verbose_name='Название камеры'),
        ),
        migrations.AlterField(
            model_name='video',
            name='rtsp_link',
            field=models.CharField(verbose_name='Ссылка на видео-поток'),
        ),
    ]
